version: "2"

services:
  proxy:
    image: nginx:1.13-alpine
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80
    depends_on:
     - api

  api:
    build: .
    depends_on:
     - db

  db:
    image: mongo:3.4
    command: --smallfiles